rpdata:
  image: jaebung/docker-gen:0.1.0
  volumes:
    - ./docker-gen/templates/:/etc/docker-gen/
    - ./docker-gen/sites-enabled/:/etc/nginx/sites-enabled/
  command: echo "Data-only container"
dockergen:
  image: jaebung/docker-gen:0.1.0
  volumes_from:
    - rpdata
  volumes:
    - /var/run/docker.sock:/docker.sock
  environment:
    - DOCKER_HOST=unix:///docker.sock
  command: /usr/bin/docker-gen -watch -only-exposed -notify-sighup=dcgenkkp_nginx_1 nginx.tmpl /etc/nginx/sites-enabled/nginx-reverse-proxy
nginx:
  build: ./nginx
  ports:
    - 80:80
  volumes_from:
    - rpdata
app:
  restart: always
  build: ./app
  expose:
    - "8080"
  environment:
    - VHOST=app
  command: java -jar app/spring-boot-sample-web-ui-0.0.0.jar
